### ISSUE TITLE
mod_fcgid: HTTP request length 136000 (so far) exceeds MaxRequestLen (131072), referer: 

### ISSUE THREAD

**Issue by sn01615** [daixianceng/microwall#1]
[Tue Oct 21 20:33:16.480030 2014] [fcgid:warn] [pid 4604:tid 1012] [client ::1:63272] mod_fcgid: HTTP request length 136000 (so far) exceeds MaxRequestLen (131072), referer: http://localhost/microwall/trunk/admin/post/writing

**Comment by daixianceng** [comment]
确保你上传的图片不超过php.ini中设置的大小
http://www.howtoforge.com/apache2-mod_fcgid-http-request-length-exceeds-maxrequestlen

**Comment by sn01615** [comment]
```
MaxRequestLen 15728640
```

我已经解决了fcgi设置里添加这个加大到15M
