### ISSUE TITLE
后台无法跳转到首页

### ISSUE THREAD

**Issue by sn01615** [daixianceng/microwall#2]
后台的网站首页链接是空的无法跳转到首页，只能复制一个选项卡
服务器：centos5+php5.6.2+mysql5.6+Apache2.4
浏览器：Google chrome 38

**Comment by daixianceng** [comment]
我用centOS6.5并未发现这种问题，可能在极少系统中才会存在吧，文件已更新：
https://github.com/daixianceng/microwall/commit/2aacf4254da70b74265ad21be2151f8202757096

**Comment by daixianceng** [comment]
让其他管理员更改用户信息，如果没有其他管理员，只能在数据库中重置默认密码：
name        password
admin       e6890cdfdf8da23ef5ea11318e106a0394fa605e

**Comment by daixianceng** [comment]
扩展并不多，gd2也是很常见的扩展，一般都会包含在php中
